apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "govuk-reports.fullname" . }}
  labels:
    {{- include "govuk-reports.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "govuk-reports.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "govuk-reports.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "govuk-reports.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            # Server configuration
            - name: SERVER_ENVIRONMENT
              value: {{ .Values.config.server.environment | quote }}
            - name: SERVER_PORT
              value: {{ .Values.config.server.port | quote }}
            - name: SERVER_HOST
              value: {{ .Values.config.server.host | quote }}
            - name: SERVER_READ_TIMEOUT
              value: {{ .Values.config.server.readTimeout | quote }}
            - name: SERVER_WRITE_TIMEOUT
              value: {{ .Values.config.server.writeTimeout | quote }}
            - name: SERVER_IDLE_TIMEOUT
              value: {{ .Values.config.server.idleTimeout | quote }}
            
            # Logging configuration
            - name: LOG_LEVEL
              value: {{ .Values.config.log.level | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.config.log.format | quote }}
            - name: LOG_OUTPUT
              value: {{ .Values.config.log.output | quote }}
            - name: LOG_TIME_FORMAT
              value: {{ .Values.config.log.timeFormat | quote }}
            - name: LOG_COLORIZE
              value: {{ .Values.config.log.colorize | quote }}
            
            # Monitoring configuration
            - name: MONITORING_METRICS_ENABLED
              value: {{ .Values.config.monitoring.metricsEnabled | quote }}
            
            # AWS configuration
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            {{- if .Values.aws.useIAMRole }}
            - name: AWS_USE_IAM_ROLE
              value: "true"
            {{- end }}
            
            # Additional environment variables
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
      
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}